# Generated by Django 5.0.6 on 2024-07-28 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0003_remove_customuser_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="university",
        ),
    ]
