# Generated by Django 5.0.6 on 2024-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_post_comment_delete_board"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("sport", models.CharField(max_length=100)),
                ("target", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=100)),
                ("day", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=50)),
                ("fee", models.IntegerField()),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
